[package]
name = "websocket-example"
version = "0.1.0"
edition = "2021"

# We optimize the release for size - quite important for the web version.
[profile.release]
opt-level = "s" # "z" doesn't work with the emscripten compiler
lto = true
panic = "abort"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-functions = { version = "0.3.0", path = "../../emscripten-functions" }
