/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn emscripten_console_log(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_console_warn(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_console_error(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_console_trace(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_out(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_err(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_dbg(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_dbg_backtrace(utf8String: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn emscripten_outn(utf8String: *const ::std::os::raw::c_char, len: usize);
}
extern "C" {
    pub fn emscripten_errn(utf8String: *const ::std::os::raw::c_char, len: usize);
}
extern "C" {
    pub fn emscripten_dbgn(utf8String: *const ::std::os::raw::c_char, len: usize);
}
extern "C" {
    pub fn emscripten_console_logf(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_console_warnf(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_console_errorf(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_console_tracef(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_outf(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_errf(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_dbgf(format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn emscripten_dbg_backtracef(format: *const ::std::os::raw::c_char, ...);
}
