[package]
name = "emscripten-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
system-headers = []

[build-dependencies]
bindgen = "0.66.1"
regex = "1.9.3"
